name: CI and CD

on:
  push:
  pull_request:
    branches:
      - main
    # types:
    #   - opened
    #   - reopened
    #   - synchronize
    #   - closed

# concurrency: preview-${{ github.ref }}

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
  

        
